### ISSUE TITLE
Select a proper abstraction for network IO

### ISSUE THREAD

**Issue by yeryomenkom** [wireapp/wire-android-sync-engine#377]
At the current moment we have two pretty similar things:
```
  type ErrorOr[T] = Future[Either[ErrorResponse, T]]
  type ErrorOrResponse[T] = CancellableFuture[Either[ErrorResponse, T]]
```

We have to remove one of them.

As part of this we need to refactor 'ErrorResponse' object. I think we need to create a hierarchy of errors for the app.

**Comment by marcoconti83** [comment]
Moving the discussion to the architecture list.
