### ISSUE TITLE
android:ndkBuild

### ISSUE THREAD

**Issue by xixixx** [wireapp/wire-android-sync-engine#474]
I use windows system， when i use the "sbt  publishM2" to build   there is  a error (zmessaging/android:ndkBuild) java.io.IOException: Cannot run program "sh": CreateProcess error=2,

**Comment by marcoconti83** [comment]
Hi @xixixx ,
It means that you are missing the `sh` shell, which is needed for our build script. I'm not a windows user so I can't suggest an actual step-by-step, but there should be ways to install it under windows too.
