### ISSUE TITLE
Supports 64-bit programs

### ISSUE THREAD

**Issue by hackerLeiWei** [wireapp/wire-android-sync-engine#558]
Hi,Is there 64 bit libsodium.so ？

**Comment by marcoconti83** [comment]
Hi @hackerLeiWei ,
thanks for asking. It's coming within a few weeks (before August 1st :D)

**Comment by marcoconti83** [comment]
See here https://github.com/wireapp/wire-android-sync-engine/pull/574

**Comment by hackerLeiWei** [comment]
@marcoconti83 Thx
